name: countries
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.8
  connectivity_plus: ^6.0.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  image: assets/logo.jpg  
  color: "#ffffff"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: font/Roboto-Regular.ttf
        - asset: font/Roboto-Bold.ttf
